stages:
  - build
  - deploy-dev
  - deploy-prod

build-frontend:
  image: node:alpine
  stage: build
  script:
    - cd frontend
    - npm install
    - CI=false npm run build

# Need some way to check python compiles
build-backend:
  stage: build
  script:
    - cd backend
    - echo "add build check and formatting"

deploy-dev:
  image: docker/compose:debian-1.29.2
  stage: deploy-dev
  script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$ID_RSA_DEV" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$KNOWN_HOSTS_DEV" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    # Docker Compose
    - COMPOSE_DOCKER_CLI_BUILD=0 DOCKER_HOST="ssh://$SERVER_USER_DEV@$SERVER_IP_DEV" MINT_ACCOUNT=$MINT_ACCOUNT SOLANA_CLIENT=$SOLANA_CLIENT RESERVE_ACCOUNT_ADDRESS=$RESERVE_ACCOUNT_ADDRESS TOKEN_OWNER=$TOKEN_OWNER SECRET_KEY=${SECRET_KEY} PAYSTACK_SECRET_KEY=${PAYSTACK_SECRET_KEY} docker-compose up --remove-orphans -d --build 
    # Remove old images
    - yes y | COMPOSE_DOCKER_CLI_BUILD=0 DOCKER_HOST="ssh://$SERVER_USER_DEV@$SERVER_IP_DEV" docker system prune --all || true
    # Ensure all containers running
    - INFO=$(COMPOSE_DOCKER_CLI_BUILD=0 DOCKER_HOST="ssh://$SERVER_USER_DEV@$SERVER_IP_DEV" docker ps)
    - if [[ $(echo $INFO | grep stablecoin_frontend_1 | wc -l) -ne 1 ]]; then echo "frontend container not running" && exit 1; else echo "frontend container check successful"; fi
    - if [[ $(echo $INFO | grep stablecoin_backend_1 | wc -l) -ne 1 ]]; then echo "backend container not running" && exit 1; else echo "backend container check successful"; fi
    - if [[ $(echo $INFO | grep stablecoin_db_1 | wc -l) -ne 1 ]]; then echo "db container not running" && exit 1; else echo "db container check successful"; fi
  only:
    - master

deploy-prod:
  image: docker/compose:debian-1.29.2
  stage: deploy-prod
  script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$ID_RSA" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    # Docker Compose
    - COMPOSE_DOCKER_CLI_BUILD=0 DOCKER_HOST="ssh://$SERVER_USER@$SERVER_IP" MINT_ACCOUNT=$MINT_ACCOUNT SOLANA_CLIENT=$SOLANA_CLIENT RESERVE_ACCOUNT_ADDRESS=$RESERVE_ACCOUNT_ADDRESS TOKEN_OWNER=$TOKEN_OWNER SECRET_KEY=${SECRET_KEY} PAYSTACK_SECRET_KEY=${PAYSTACK_SECRET_KEY} docker-compose up --remove-orphans -d --build 
    # Remove old images
    - yes y | COMPOSE_DOCKER_CLI_BUILD=0 DOCKER_HOST="ssh://$SERVER_USER@$SERVER_IP" docker system prune --all || true
    # Ensure all containers running
    - INFO=$(COMPOSE_DOCKER_CLI_BUILD=0 DOCKER_HOST="ssh://$SERVER_USER@$SERVER_IP" docker ps)
    - if [[ $(echo $INFO | grep stablecoin_frontend_1 | wc -l) -ne 1 ]]; then echo "frontend container not running" && exit 1; else echo "frontend container check successful"; fi
    - if [[ $(echo $INFO | grep stablecoin_backend_1 | wc -l) -ne 1 ]]; then echo "backend container not running" && exit 1; else echo "backend container check successful"; fi
    - if [[ $(echo $INFO | grep stablecoin_db_1 | wc -l) -ne 1 ]]; then echo "db container not running" && exit 1; else echo "db container check successful"; fi
  only:
    - master
  when: manual