stages:
  - style
  - build
  - test
  - deploy-dev
  - deploy-prod

style-rcoin:
  image: node:alpine
  stage: style
  script:
    - npm install prettier
    - npx prettier --check "RCoin/src/**/*.tsx" --config RCoin/.prettierrc.js

build-frontend:
  image: docker/compose:debian-1.29.2
  stage: build
  script:
    - "command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval $(ssh-agent -s)
    - echo "$ID_RSA" | tr -d '\r' | ssh-add -
    - echo "$ID_RSA_SIGNER_PROD" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - COMPOSE_DOCKER_CLI_BUILD=0 DOCKER_HOST="ssh://$SERVER_USER@$SERVER_IP" docker build -t rcoin-frontend ./frontend
    - COMPOSE_DOCKER_CLI_BUILD=0 DOCKER_HOST="ssh://$SERVER_USER@$SERVER_IP" docker image tag rcoin-frontend 146.169.40.88:5000/rcoin-frontend:$CI_COMMIT_SHA
    - COMPOSE_DOCKER_CLI_BUILD=0 DOCKER_HOST="ssh://$SERVER_USER@$SERVER_IP" docker push 146.169.40.88:5000/rcoin-frontend:$CI_COMMIT_SHA

build-backend:
  image: docker/compose:debian-1.29.2
  stage: build
  script:
    - "command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval $(ssh-agent -s)
    - echo "$ID_RSA" | tr -d '\r' | ssh-add -
    - echo "$ID_RSA_SIGNER_PROD" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - COMPOSE_DOCKER_CLI_BUILD=0 DOCKER_HOST="ssh://$SERVER_USER@$SERVER_IP" docker build -t rcoin-backend ./backend
    - COMPOSE_DOCKER_CLI_BUILD=0 DOCKER_HOST="ssh://$SERVER_USER@$SERVER_IP" docker image tag rcoin-backend 146.169.40.88:5000/rcoin-backend:$CI_COMMIT_SHA
    - COMPOSE_DOCKER_CLI_BUILD=0 DOCKER_HOST="ssh://$SERVER_USER@$SERVER_IP" docker push 146.169.40.88:5000/rcoin-backend:$CI_COMMIT_SHA

build-signer:
  image: docker/compose:debian-1.29.2
  stage: build
  script:
    - "command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval $(ssh-agent -s)
    - echo "$ID_RSA" | tr -d '\r' | ssh-add -
    - echo "$ID_RSA_SIGNER_PROD" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    # Signer backend image
    - COMPOSE_DOCKER_CLI_BUILD=0 DOCKER_HOST="ssh://$SERVER_USER@$SERVER_IP" docker build -t rcoin-signer-backend ./signer
    - COMPOSE_DOCKER_CLI_BUILD=0 DOCKER_HOST="ssh://$SERVER_USER@$SERVER_IP" docker image tag rcoin-signer-backend 146.169.40.88:5000/rcoin-signer-backend:$CI_COMMIT_SHA
    - COMPOSE_DOCKER_CLI_BUILD=0 DOCKER_HOST="ssh://$SERVER_USER@$SERVER_IP" docker push 146.169.40.88:5000/rcoin-signer-backend:$CI_COMMIT_SHA
    # Signer proxy Image
    - COMPOSE_DOCKER_CLI_BUILD=0 DOCKER_HOST="ssh://$SERVER_USER@$SERVER_IP" docker build -t rcoin-signer-proxy ./signer/nginx
    - COMPOSE_DOCKER_CLI_BUILD=0 DOCKER_HOST="ssh://$SERVER_USER@$SERVER_IP" docker image tag rcoin-signer-proxy 146.169.40.88:5000/rcoin-signer-proxy:$CI_COMMIT_SHA
    - COMPOSE_DOCKER_CLI_BUILD=0 DOCKER_HOST="ssh://$SERVER_USER@$SERVER_IP" docker push 146.169.40.88:5000/rcoin-signer-proxy:$CI_COMMIT_SHA

test-backend:
  stage: test
  image: python:3.9
  before_script:
    - cd backend
    - pip install -r requirements.txt
  script:
    - pytest -v

deploy-dev:
  image: docker/compose:debian-1.29.2
  stage: deploy-dev
  script:
    - "command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval $(ssh-agent -s)
    - echo "$ID_RSA_DEV" | tr -d '\r' | ssh-add -
    - echo "$ID_RSA_SIGNER_DEV" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$KNOWN_HOSTS_DEV" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    # Docker Compose Main backend
    - COMPOSE_DOCKER_CLI_BUILD=0 DOCKER_HOST="ssh://$SERVER_USER_DEV@$SERVER_IP_DEV" CI_COMMIT_SHA=$CI_COMMIT_SHA FEE_ACCOUNT=$DEV_FEE_ACCOUNT SIGNER_BACKEND_URL=$DEV_SIGNER_BACKEND_URL MINT_ACCOUNT=$DEV_MINT_ACCOUNT SOLANA_CLIENT=$SOLANA_CLIENT RESERVE_ACCOUNT=$DEV_RESERVE_ACCOUNT TOKEN_OWNER=$DEV_TOKEN_OWNER MULTISIG_ACCOUNT=$DEV_MULTISIG_ACCOUNT SIGNER_1=$DEV_SIGNER_1  SIGNER_1_PUBKEY=$DEV_SIGNER_1_PUBKEY SIGNER_2_PUBKEY=$DEV_SIGNER_2_PUBKEY PAYSTACK_SECRET_KEY=${DEV_PAYSTACK_SECRET_KEY} DATABASE_URL=${DATABASE_URL} REDIS_PASS=${REDIS_PASS} GMAIL_PASSWORD=${DEV_GMAIL_PASSWORD} FIREBASE_JSON=${FIREBASE_JSON} PAYSTACK_EMAIL=${PAYSTACK_EMAIL} PAYSTACK_PASSWORD=${PAYSTACK_PASSWORD} PAYSTACK_INTEGRATION=${PAYSTACK_INTEGRATION_DEV} docker-compose --file docker-compose-dev.yml --profile main up --remove-orphans -d --build
    - yes y | COMPOSE_DOCKER_CLI_BUILD=0 DOCKER_HOST="ssh://$SERVER_USER_DEV@$SERVER_IP_DEV" docker system prune --all || true
    # # Docker Compose signer
    - COMPOSE_DOCKER_CLI_BUILD=0 DOCKER_HOST="ssh://$SERVER_USER_DEV@$SERVER_IP_SIGNER_DEV" CI_COMMIT_SHA=$CI_COMMIT_SHA SIGNER_2=$DEV_SIGNER_2 docker-compose --file docker-compose-dev.yml --profile signer up --remove-orphans -d --build
    - yes y | COMPOSE_DOCKER_CLI_BUILD=0 DOCKER_HOST="ssh://$SERVER_USER_DEV@$SERVER_IP_SIGNER_DEV" docker system prune --all || true
    # Ensure all containers running on main backend
    - INFO=$(COMPOSE_DOCKER_CLI_BUILD=0 DOCKER_HOST="ssh://$SERVER_USER_DEV@$SERVER_IP_DEV" docker ps)
    - if [[ $(echo $INFO | grep stablecoin_frontend_1 | wc -l) -ne 1 ]]; then echo "frontend container not running" && exit 1; else echo "frontend container check successful"; fi
    - if [[ $(echo $INFO | grep stablecoin_backend_1 | wc -l) -ne 1 ]]; then echo "backend container not running" && exit 1; else echo "backend container check successful"; fi
    - if [[ $(echo $INFO | grep stablecoin_db_1 | wc -l) -ne 1 ]]; then echo "db container not running" && exit 1; else echo "db container check successful"; fi
    - if [[ $(echo $INFO | grep stablecoin_redis_1 | wc -l) -ne 1 ]]; then echo "redis container not running" && exit 1; else echo "redis container check successful"; fi
    # Ensure all containers running on signer backend
    - INFO=$(COMPOSE_DOCKER_CLI_BUILD=0 DOCKER_HOST="ssh://$SERVER_USER_DEV@$SERVER_IP_SIGNER_DEV" docker ps)
    - if [[ $(echo $INFO | grep stablecoin_signer-proxy_1 | wc -l) -ne 1 ]]; then echo "signer nginx container not running" && exit 1; else echo "signer nginx container check successful"; fi
    - if [[ $(echo $INFO | grep stablecoin_signer-backend_1 | wc -l) -ne 1 ]]; then echo "signer backend container not running" && exit 1; else echo "signer backend container check successful"; fi
  only:
    - master

deploy-prod:
  image: docker/compose:debian-1.29.2
  stage: deploy-prod
  script:
    - "command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval $(ssh-agent -s)
    - echo "$ID_RSA" | tr -d '\r' | ssh-add -
    - echo "$ID_RSA_SIGNER_PROD" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts    
    # Docker Swarm Main backend
    - COMPOSE_DOCKER_CLI_BUILD=0 DOCKER_HOST="ssh://$SERVER_USER@$SERVER_IP" CI_COMMIT_SHA=$CI_COMMIT_SHA FEE_ACCOUNT=$PROD_FEE_ACCOUNT SIGNER_BACKEND_URL=$PROD_SIGNER_BACKEND_URL MINT_ACCOUNT=$PROD_MINT_ACCOUNT SOLANA_CLIENT=$SOLANA_CLIENT RESERVE_ACCOUNT=$PROD_RESERVE_ACCOUNT TOKEN_OWNER=$PROD_TOKEN_OWNER MULTISIG_ACCOUNT=$PROD_MULTISIG_ACCOUNT SIGNER_1=$PROD_SIGNER_1 SIGNER_2=$PROD_SIGNER_2 SIGNER_1_PUBKEY=$PROD_SIGNER_1_PUBKEY SIGNER_2_PUBKEY=$PROD_SIGNER_2_PUBKEY  PAYSTACK_SECRET_KEY=${PROD_PAYSTACK_SECRET_KEY} DATABASE_URL=${DATABASE_URL} REDIS_PASS=${REDIS_PASS} GMAIL_PASSWORD=${PROD_GMAIL_PASSWORD} FIREBASE_JSON=${FIREBASE_JSON} PAYSTACK_EMAIL=${PAYSTACK_EMAIL} PAYSTACK_PASSWORD=${PAYSTACK_PASSWORD} PAYSTACK_INTEGRATION=${PAYSTACK_INTEGRATION_PROD} docker stack deploy --compose-file=docker-compose-main.yml rcoin
    - yes y | COMPOSE_DOCKER_CLI_BUILD=0 DOCKER_HOST="ssh://$SERVER_USER@$SERVER_IP" docker system prune --all || true
    # Docker Swarm signer
    - COMPOSE_DOCKER_CLI_BUILD=0 DOCKER_HOST="ssh://$SERVER_USER@$SERVER_IP_SIGNER_PROD" CI_COMMIT_SHA=$CI_COMMIT_SHA SIGNER_2=$PROD_SIGNER_2 docker stack deploy --compose-file=docker-compose-signer.yml rcoin
    - yes y | COMPOSE_DOCKER_CLI_BUILD=0 DOCKER_HOST="ssh://$SERVER_USER@$SERVER_IP_SIGNER_PROD" docker system prune --all || true
    # Wait a minute for containers to spin up
    - sleep 60
    # Ensure all containers running on main backend
    - if [[ $(COMPOSE_DOCKER_CLI_BUILD=0 DOCKER_HOST="ssh://$SERVER_USER@$SERVER_IP" docker service ls | grep rcoin_frontend | awk '{print $4}' | head -c 1) -eq 0 ]]; then echo "frontend container not running" && exit 1; else echo "frontend container check successful"; fi
    - if [[ $(COMPOSE_DOCKER_CLI_BUILD=0 DOCKER_HOST="ssh://$SERVER_USER@$SERVER_IP" docker service ls | grep rcoin_backend | awk '{print $4}' | head -c 1) -eq 0 ]]; then echo "backend container not running" && exit 1; else echo "backend container check successful"; fi
    - if [[ $(COMPOSE_DOCKER_CLI_BUILD=0 DOCKER_HOST="ssh://$SERVER_USER@$SERVER_IP" docker service ls | grep rcoin_db | awk '{print $4}' | head -c 1) -eq 0 ]]; then echo "db container not running" && exit 1; else echo "db container check successful"; fi
    - if [[ $(COMPOSE_DOCKER_CLI_BUILD=0 DOCKER_HOST="ssh://$SERVER_USER@$SERVER_IP" docker service ls | grep rcoin_redis | awk '{print $4}' | head -c 1) -eq 0 ]]; then echo "redis container not running" && exit 1; else echo "redis container check successful"; fi
    # Ensure all containers running on signer backend
    - if [[ $(COMPOSE_DOCKER_CLI_BUILD=0 DOCKER_HOST="ssh://$SERVER_USER@$SERVER_IP_SIGNER_PROD" docker service ls | grep rcoin_signer-proxy | awk '{print $4}' | head -c 1) -eq 0 ]]; then echo "signer nginx container not running" && exit 1; else echo "signer nginx container check successful"; fi
    - if [[ $(COMPOSE_DOCKER_CLI_BUILD=0 DOCKER_HOST="ssh://$SERVER_USER@$SERVER_IP_SIGNER_PROD" docker service ls | grep rcoin_signer-backend | awk '{print $4}' | head -c 1) -eq 0 ]]; then echo "signer backend container not running" && exit 1; else echo "signer backend container check successful"; fi
  # only:
  #   - master
  # when: manual