version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - 443:443
    depends_on:
      - backend
    volumes:
      - /etc/certs:/etc/nginx/certs

  backend:
    build: ./backend
    environment:
      - DEV=${DEV}
      - DEV_SOLANA_CLIENT=${DEV_SOLANA_CLIENT}
      - DEV_MINT_ACCOUNT=${DEV_MINT_ACCOUNT}
      - DEV_RESERVE_ACCOUNT_ADDRESS=${DEV_RESERVE_ACCOUNT_ADDRESS}
      - DEV_TOKEN_OWNER=${DEV_TOKEN_OWNER}
      - DEV_SECRET_KEY=${DEV_SECRET_KEY}
      - DEV_PAYSTACK_SECRET_KEY=${DEV_PAYSTACK_SECRET_KEY}
      - DEV_DATABASE_URL=${DEV_DATABASE_URL}
      - DEV_GMAIL_PASSWORD=${DEV_GMAIL_PASSWORD}

      - PROD_SOLANA_CLIENT=${PROD_SOLANA_CLIENT}
      - PROD_MINT_ACCOUNT=${PROD_MINT_ACCOUNT}
      - PROD_RESERVE_ACCOUNT_ADDRESS=${PROD_RESERVE_ACCOUNT_ADDRESS}
      - PROD_TOKEN_OWNER=${PROD_TOKEN_OWNER}
      - PROD_SECRET_KEY=${PROD_SECRET_KEY}
      - PROD_PAYSTACK_SECRET_KEY=${PROD_PAYSTACK_SECRET_KEY}
      - PROD_DATABASE_URL=${PROD_DATABASE_URL}
      - PROD_GMAIL_PASSWORD=${PROD_GMAIL_PASSWORD}

      - REDIS_PASS=${REDIS_PASS}
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - /etc/certs:/etc/nginx/certs

  db:
    image: postgres:alpine
    restart: always
    # ports:
    # - 5432:5432
    environment:
      - POSTGRES_USER=stablecoin_database
      - POSTGRES_PASSWORD=stablecoin
      - POSTGRES_HOST=localhost
    volumes:
      - db:/var/lib/postgresql/data/

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASS}
    volumes:
      - redis:/data

volumes:
  db:
    driver: local
  redis:
    driver: local
