version: "3.8"
services:
  signer-backend:
    image: 146.169.40.88:5000/rcoin-signer-backend
    environment:
      - SIGNER_2=${SIGNER_2}

  signer-proxy:
    image: 146.169.40.88:5000/rcoin-signer-proxy
    ports:
      - 80:80
    depends_on:
      - signer-backend
